FROM golang:1.16.15-alpine

WORKDIR /usr/src/app

COPY go* .

RUN adduser -D appuser && \
    chown appuser . && \
    go mod download

COPY . .

RUN go build && \
    chmod +x ./server

EXPOSE 8080

USER appuser

CMD ./server