FROM node:16.20.2

WORKDIR /usr/src/app

COPY package* .

RUN npm ci && \
    npm i -g serve

COPY . .

RUN npm run build && \
    useradd -m appuser && \
    chown appuser .

EXPOSE 5000

USER appuser

CMD serve -s -l 5000 build