FROM node:16.20.2

WORKDIR /usr/src/app

RUN useradd -m appuser

RUN chown appuser .

RUN npm i -g serve

COPY package* .

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 5000

USER appuser

CMD serve -s -l 5000 build