version: '3.8'

services:
  example-backend-service:
    image: example-backend
    container_name: example-backend
    build: .
    ports:
      - 8080:8080
  example-frontend-service:
    image: example-frontend
    container_name: example-frontend
    build: .
    ports:
      - 5000:5000